/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Proxy } from "../Proxy";

export class Proxy__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Proxy> {
    return super.deploy(overrides || {}) as Promise<Proxy>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Proxy {
    return super.attach(address) as Proxy;
  }
  connect(signer: Signer): Proxy__factory {
    return super.connect(signer) as Proxy__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Proxy {
    return new Contract(address, _abi, signerOrProvider) as Proxy;
  }
}

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_facet1",
        type: "address",
      },
    ],
    name: "initializor1",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101e6806100206000396000f3fe6080604052600436106100225760003560e01c806385d9b2431461008557610029565b3661002957005b61006060405180604001604052806016815260200175141c9bde1e4e8811985b1b189858dac818d85b1b195960521b8152506100c4565b60015460003681823780813683855af491503d81823e818015610081573d82f35b3d82fd5b34801561009157600080fd5b506100c26100a036600461012b565b600180546001600160a01b0319166001600160a01b0392909216919091179055565b005b610107816040516024016100d8919061015b565b60408051601f198184030181529190526020810180516001600160e01b031663104c13eb60e21b17905261010a565b50565b80516a636f6e736f6c652e6c6f67602083016000808483855afa5050505050565b60006020828403121561013d57600080fd5b81356001600160a01b038116811461015457600080fd5b9392505050565b600060208083528351808285015260005b818110156101885785810183015185820160400152820161016c565b8181111561019a576000604083870101525b50601f01601f191692909201604001939250505056fea264697066735822122038aa185447ff55942939507bca722e861e90ce2a45c9c4934848e394afa8f21464736f6c63430008070033";
