/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { ERC20Token } from "./ERC20Token";
export type { FacetA } from "./FacetA";
export type { FacetB } from "./FacetB";
export type { Proxy } from "./Proxy";
export type { ProxyTest } from "./ProxyTest";

export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { ERC20Token__factory } from "./factories/ERC20Token__factory";
export { FacetA__factory } from "./factories/FacetA__factory";
export { FacetB__factory } from "./factories/FacetB__factory";
export { Proxy__factory } from "./factories/Proxy__factory";
export { ProxyTest__factory } from "./factories/ProxyTest__factory";
