/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TestContract1Interface extends ethers.utils.Interface {
  functions: {
    "getValue()": FunctionFragment;
    "ownerable()": FunctionFragment;
    "setValue(string)": FunctionFragment;
    "val()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getValue", values?: undefined): string;
  encodeFunctionData(functionFragment: "ownerable", values?: undefined): string;
  encodeFunctionData(functionFragment: "setValue", values: [string]): string;
  encodeFunctionData(functionFragment: "val", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "val", data: BytesLike): Result;

  events: {};
}

export class TestContract1 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TestContract1Interface;

  functions: {
    getValue(overrides?: Overrides): Promise<ContractTransaction>;

    "getValue()"(overrides?: Overrides): Promise<ContractTransaction>;

    ownerable(overrides?: Overrides): Promise<ContractTransaction>;

    "ownerable()"(overrides?: Overrides): Promise<ContractTransaction>;

    setValue(_val: string, overrides?: Overrides): Promise<ContractTransaction>;

    "setValue(string)"(
      _val: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    val(overrides?: CallOverrides): Promise<[string]>;

    "val()"(overrides?: CallOverrides): Promise<[string]>;
  };

  getValue(overrides?: Overrides): Promise<ContractTransaction>;

  "getValue()"(overrides?: Overrides): Promise<ContractTransaction>;

  ownerable(overrides?: Overrides): Promise<ContractTransaction>;

  "ownerable()"(overrides?: Overrides): Promise<ContractTransaction>;

  setValue(_val: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setValue(string)"(
    _val: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  val(overrides?: CallOverrides): Promise<string>;

  "val()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getValue(overrides?: CallOverrides): Promise<void>;

    "getValue()"(overrides?: CallOverrides): Promise<void>;

    ownerable(overrides?: CallOverrides): Promise<void>;

    "ownerable()"(overrides?: CallOverrides): Promise<void>;

    setValue(_val: string, overrides?: CallOverrides): Promise<void>;

    "setValue(string)"(_val: string, overrides?: CallOverrides): Promise<void>;

    val(overrides?: CallOverrides): Promise<string>;

    "val()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getValue(overrides?: Overrides): Promise<BigNumber>;

    "getValue()"(overrides?: Overrides): Promise<BigNumber>;

    ownerable(overrides?: Overrides): Promise<BigNumber>;

    "ownerable()"(overrides?: Overrides): Promise<BigNumber>;

    setValue(_val: string, overrides?: Overrides): Promise<BigNumber>;

    "setValue(string)"(_val: string, overrides?: Overrides): Promise<BigNumber>;

    val(overrides?: CallOverrides): Promise<BigNumber>;

    "val()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getValue(overrides?: Overrides): Promise<PopulatedTransaction>;

    "getValue()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    ownerable(overrides?: Overrides): Promise<PopulatedTransaction>;

    "ownerable()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setValue(
      _val: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setValue(string)"(
      _val: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    val(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "val()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
